### ISSUE TITLE
In Nether, Skeletons should Spawn too

### ISSUE THREAD

**Issue by PocketMiner92** [xodamcm/BetterMobsOverworld#2]
In Vanilla, Skeletons Spawn in Nether Fortress

**Comment by xodamcm** [comment]
Downlod BetterMobsNether, Skeleton good spawn, you can see on the youtube video, or increase number of skeleton in config

**Comment by PocketMiner92** [comment]
Only Wither Skeletons.

**Comment by xodamcm** [comment]
Yeah download the last devs, of OverworldMobs & Nether coming soon because i upload the bad version
