### ISSUE TITLE
Whitelist Or blacklist spawn worlds

### ISSUE THREAD

**Issue by nebotLol** [xodamcm/BetterMobsOverworld#4]
How about adding different types of choices where mobs will spawn? as in plugin_list on PM4.
 Whitelist - list of worlds, only the ones that WILL spawn mobs. 
Blacklist - only worlds that WILL NOT spawn mobs.

**Comment by nebotLol** [comment]
wish

**Comment by xodamcm** [comment]
I won't touch the mob spawn, that's fine with me
that would be nice, i have already put whitelist for my server, i don't have time to edit the plugin here, so one day maybe

**Comment by nebotLol** [comment]
Worlds generated automatically by some plugins - not always have the same name. a striking example of Oneblock, which creates a world with the nickname of the player, there is instantly spawned all the mobs of Nether, Overworld and end, which is very bad for the game. It would be much easier to allow mobs to spawn in their worlds than to manually enter each new world created =)

**Comment by xodamcm** [comment]
I have desactivate spawn mobs on playername world (like OneBlock/SkyBlock, & also ai-playername world, for AcidIsland) wait, il will did it for Nether & End plugins
