### ISSUE TITLE
PM5

### ISSUE THREAD

**Issue by nebotLol** [xodamcm/BetterMobsOverworld#7]
Hi! What about update this amazing plugin to PM5? would be cool

**Comment by xodamcm** [comment]
I will!!! 😁

**Comment by xodamcm** [comment]
https://youtu.be/YzkgtpayMDc
https://poggit.pmmp.io/ci/xodamcm/BetterMobsOverworld-PM5/~

**Comment by nebotLol** [comment]
Great! i hope you update other BetterMobs (End and nether) =)

**Comment by xodamcm** [comment]
Download Link (PM5): MobsOverworld
https://poggit.pmmp.io/ci/xodamcm/BetterMobsOverworld-PM5/~

Download Link (PM5): BetterEndMobs
https://poggit.pmmp.io/ci/xodamcm/BetterMobsEnd-PM5/~

Download Link (PM5): BetterMobsNether
https://poggit.pmmp.io/ci/xodamcm/BetterMobsNether-PM5/~

😊

**Comment by nebotLol** [comment]
thank you very much! =)

**Comment by TheLemzz** [comment]
Does not work
